server:
  port: 8888
spring:
  datasource:
    platform: h2
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
logging:
  level:
    org.eclipse.jetty: trace